### ISSUE TITLE
Problems with CocoaPod

### ISSUE THREAD

**Issue by lfarah** [bguidolim/AppReviewTimes-iOS#3]
Im getting this when doing "pod install":

```
[!] The version of CocoaPods used to generate the lockfile (0.36.0.beta.2) is higher than the version of the current executable (0.35.0). Incompatibility issues may arise."
```

I'm very unexperienced with CocoaPods. It would be cool to have a download option.

**Comment by gmogames** [comment]
You don;t have to worry. This is just a warning.

---

Guilherme Mogames
gmogames@gmail.com

**Comment by lfarah** [comment]
Oh, thanks!
